version: "2"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - .data/logs/mosquitto/:/mosquitto/log/
      - iot-edge-mosquitto:/mosquitto/data/
    networks:
      - iot-edge

  influxdb:
    container_name: influxdb
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - iot-edge-influxdb-data:/var/lib/influxdb2
      - iot-edge-influxdb-conf:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    networks:
      - iot-edge

  telegraf:
    container_name: telegraf
    image: telegraf
    restart: always
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot-edge
    
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - iot-edge-grafana-data:/var/lib/grafana
      - .data/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - iot-edge


networks:
  iot-edge:
    name: iot-edge

volumes:
  iot-edge-mosquitto:
  iot-edge-grafana-data:
  iot-edge-influxdb-data:
  iot-edge-influxdb-conf:
  iot-edge-mosquitto-data:
